name: Manual Test Run

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - homepage
        - registration

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Run tests
      run: |
        if ("${{ github.event.inputs.test_suite }}" -eq "homepage") {
          dotnet test --filter "FullyQualifiedName~HomePage"
        } elseif ("${{ github.event.inputs.test_suite }}" -eq "registration") {
          dotnet test --filter "FullyQualifiedName~Registration"
        } else {
          dotnet test
        }
      env:
        DOTNET_ENVIRONMENT: Test

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: TestResults

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        gh_pages: gh-pages
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history