name: Manual Test Run

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - homepage
        - registration
permissions:
  contents: write

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run tests
      run: |
        if [ "${{ github.event.inputs.test_suite }}" = "homepage" ]; then
          dotnet test --filter "FullyQualifiedName~HomePage"
        elif [ "${{ github.event.inputs.test_suite }}" = "registration" ]; then
          dotnet test --filter "FullyQualifiedName~Registration"
        else
          dotnet test
        fi
      env:
        DOTNET_ENVIRONMENT: Test

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: TestResults

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        gh_pages: gh-pages
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history