name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@master

    - name: Start ChromeDriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        DISPLAY: :99

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-results
        path: TestResults